common/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>구독내역</label>
    <nameField>
        <displayFormat>S-{YY}{MM}{000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>구독내역</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Subscription__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>아동 이름</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>구독내역들</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>구독 종료일</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>과정명</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Name</field>
            <operation>equals</operation>
            <valueField>Product2.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>구독내역</relationshipLabel>
    <relationshipName>ProductName</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>구독 시작일</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>개월수</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/classes/SubscriptionController.cls
public with sharing class SubscriptionController {
    @AuraEnabled(cacheable=true)
    public static List<Subscription__c> getSubscriptions(Id contactId) {
        return [
            SELECT Id, Term__c, StartDate__c, EndDate__c,
                   ProductId__r.Name
            FROM Subscription__c
            WHERE ContactId__c = :contactId
            ORDER BY StartDate__c DESC
        ];
    }
}