common/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>구독내역</label>
    <nameField>
        <displayFormat>S-{YY}{MM}{000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>구독내역</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Subscription__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>아동 이름</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>구독내역들</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/ContractId__c.field-meta.xml
<CustomField>
    <fullName>ContractId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>구독내역들을 Summary 하여 볼 수 있는 계약 내용 조회</description>
    <label>계약 ID</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>구독내역</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>구독 종료일</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>과정명</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Name</field>
            <operation>equals</operation>
            <valueField>Product2.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>구독내역</relationshipLabel>
    <relationshipName>ProductName</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>구독 시작일</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>구독상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>진행중</fullName>
            </value>
            <value>
                <fullName>완료</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>취소</label>
            </value>
            <value>
                <fullName>진행전</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>개월수</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/classes/SingleContactContractGenerator.cls
public class SingleContactContractGenerator {

    public static void createContractForContact(Id contactId) {
        List<Subscription__c> subs = [
            SELECT Id, Term__c, StartDate__c, EndDate__c,
                   ContactId__c, ContactId__r.AccountId,
                   ProductId__r.MonthlyPrice__c, ProductId__r.Name
            FROM Subscription__c
            WHERE ContactId__c = :contactId
              AND ContractId__c = NULL
              AND Status__c != '취소됨'
        ];

        if (subs.isEmpty()) {
            System.debug('📭 계약되지 않은 구독내역이 없습니다.');
            return;
        }

        Id accountId = subs[0].ContactId__r.AccountId;
        if (accountId == null) {
            System.debug('❗ Contact에 학부모(Account)가 연결되지 않았습니다.');
            return;
        }

        Decimal total = 0;
        for (Subscription__c s : subs) {
            Decimal unit = s.ProductId__r.MonthlyPrice__c;
            Integer months = s.Term__c != null ? s.Term__c.intValue() : 0;
            total += unit * months;
        }

        Contract con = new Contract(
            AccountId = accountId,
            Status = 'Draft',
            Original_Total_Amount__c = total
        );
        insert con;

        for (Subscription__c s : subs) {
            s.ContractId__c = con.Id;
        }
        update subs;

        System.debug('✅ 계약 생성 완료! ContractId: ' + con.Id);
    }
}