common/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>구독내역</label>
    <nameField>
        <displayFormat>S-{YY}{MM}{000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>구독내역</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Subscription__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>아동 이름</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>구독내역들</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Subscription__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>과정명</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Name</field>
            <operation>equals</operation>
            <valueField>Product2.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>구독내역</relationshipLabel>
    <relationshipName>ProductName</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/classes/ChildProfileController.cls
public with sharing class ChildProfileController {
    @AuraEnabled(cacheable=true)
    public static List<String> getSubjectFamilies(Id contactId) {
        Set<String> subjectSet = new Set<String>();

        List<Subscription__c> subs = [
            SELECT ProductId__r.Family
            FROM Subscription__c
            WHERE ContactId__c = :contactId
              AND ProductId__r.Family != null
        ];

        for (Subscription__c sub : subs) {
            subjectSet.add(sub.ProductId__r.Family);
        }

        return new List<String>(subjectSet);
    }
}